package brickgame;

import javax.microedition.lcdui.Graphics;
import javax.microedition.lcdui.game.GameCanvas;

/** Thin MIDP shell: input, timing and presentation are delegated to modules. */
final class BrickCanvas extends GameCanvas implements Runnable {

    private static final int TARGET_FPS = 30;
    private static final int FRAME_TIME = 1000 / TARGET_FPS;
    private static final int FRAME_REMAINDER = 1000 % TARGET_FPS;
    private static final int MAX_CATCH_UP_FRAMES = 4;

    private final GameEngine engine = new GameEngine();
    private final GameSnapshot snapshot = new GameSnapshot();
    private final BrickRenderer renderer = new BrickRenderer();
    private final InputRepeater input = new InputRepeater();

    private volatile boolean running;
    private Thread loop;
    private volatile boolean redraw = true;
    private long lastStatusSecond = -1L;
    private int frameRemainder;

    BrickCanvas() {
        super(false);
        setFullScreenMode(true);
    }

    synchronized void start() {
        if (running) {
            return;
        }
        running = true;
        redraw = true;
        frameRemainder = 0;
        lastStatusSecond = -1L;
        loop = new Thread(this);
        loop.start();
    }

    synchronized void stop() {
        running = false;
        input.clear();
        loop = null;
    }

    void setSystemPaused(boolean paused) {
        input.clear();
        engine.setSystemPaused(paused);
        redraw = true;
    }

    public void run() {
        long nextFrame = System.currentTimeMillis();
        while (running) {
            long now = System.currentTimeMillis();
            long wait = nextFrame - now;
            if (wait > 0L) {
                sleep(wait);
                continue;
            }

            int catchUp = 0;
            do {
                input.tick(nextFrame, engine);
                engine.tick(nextFrame);
                nextFrame = advanceFrame(nextFrame);
                catchUp++;
            } while (nextFrame <= now && catchUp < MAX_CATCH_UP_FRAMES);

            if (nextFrame <= now) {
                nextFrame = now + FRAME_TIME;
                frameRemainder = 0;
            }
            if (engine.copySnapshot(snapshot)) {
                redraw = true;
            }
            if (getWidth() == 320 && getHeight() == 240) {
                long statusSecond = now / 1000L;
                if (statusSecond != lastStatusSecond) {
                    lastStatusSecond = statusSecond;
                    redraw = true;
                }
            }
            if (redraw) {
                drawFrame();
                redraw = false;
            }
        }
    }

    private long advanceFrame(long deadline) {
        deadline += FRAME_TIME;
        frameRemainder += FRAME_REMAINDER;
        if (frameRemainder >= TARGET_FPS) {
            deadline++;
            frameRemainder -= TARGET_FPS;
        }
        return deadline;
    }

    private static void sleep(long delay) {
        try {
            Thread.sleep(delay);
        } catch (InterruptedException ignored) {
        }
    }

    public void paint(Graphics graphics) {
        engine.copySnapshot(snapshot);
        renderer.render(graphics, snapshot, getWidth(), getHeight());
    }

    private void drawFrame() {
        try {
            Graphics graphics = getGraphics();
            renderer.render(graphics, snapshot, getWidth(), getHeight());
            flushGraphics();
        } catch (Throwable ignored) {
            // Hidden MIDlets and a few old implementations reject active paint.
        }
    }

    protected void keyPressed(int keyCode) {
        int action = mapKey(keyCode);
        if (action != GameEngine.ACTION_NONE) {
            input.press(action, System.currentTimeMillis(), engine);
        }
    }

    protected void keyRepeated(int keyCode) {
        // Repetition is generated by InputRepeater with stable Nokia timing.
    }

    protected void keyReleased(int keyCode) {
        int action = mapKey(keyCode);
        if (action != GameEngine.ACTION_NONE) {
            input.release(action);
        }
    }

    private int mapKey(int keyCode) {
        if (keyCode == KEY_NUM2) {
            return GameEngine.ACTION_UP;
        }
        if (keyCode == KEY_NUM8) {
            return GameEngine.ACTION_DOWN;
        }
        if (keyCode == KEY_NUM4) {
            return GameEngine.ACTION_LEFT;
        }
        if (keyCode == KEY_NUM6) {
            return GameEngine.ACTION_RIGHT;
        }
        if (keyCode == KEY_NUM5) {
            return GameEngine.ACTION_FIRE;
        }
        if (keyCode == KEY_NUM0 || keyCode == -6) {
            return GameEngine.ACTION_PAUSE;
        }
        if (keyCode == KEY_POUND || keyCode == -7) {
            return GameEngine.ACTION_MENU;
        }
        try {
            int action = getGameAction(keyCode);
            if (action == UP) {
                return GameEngine.ACTION_UP;
            }
            if (action == DOWN) {
                return GameEngine.ACTION_DOWN;
            }
            if (action == LEFT) {
                return GameEngine.ACTION_LEFT;
            }
            if (action == RIGHT) {
                return GameEngine.ACTION_RIGHT;
            }
            if (action == FIRE) {
                return GameEngine.ACTION_FIRE;
            }
        } catch (IllegalArgumentException ignored) {
        }
        return GameEngine.ACTION_NONE;
    }
}
